### PR TITLE
resolve #158

### LINKED ISSUE #158: Element\DateTime construction w/ invalid min / max validation values causes form to not work w/o a clear reason why
Given the following array notation, the `DateTime` Element will indicate that the date information provided on submission is invalid. The cause for this is because the Element is presuming that the min / max validators will ALWAYS construct to a `\DateTime` object; however, in this case they return to null because the format is not compliant with the expected constant's string.

```php
[
    'spec' => [
        'name' => 'start_time',
        'type' => Zend\Form\Element\DateTime::class,
        'options' => [
            'label' => 'Appointment Date',
        ],
        'attributes' => [
            'min' => '2017-01-01',
            'max' => '2017-12-29',
            'step' => 1,
        ],
    ],
]
```

The following spec does work:

```php
[
    'spec' => [
        'name' => 'start_time',
        'type' => Zend\Form\Element\DateTime::class,
        'options' => [
            'label' => 'Appointment Date',
        ],
        'attributes' => [
            'min' => '2017-01-01T00:00+00:00',
            'max' => '2017-12-29T23:59+00:00',
            'step' => 1,
        ],
    ],
]
```

### PR DESCRIPTION
**Pull request by jackdpeterson**
Throws an InvalidArgumentException when one attempts to create a DateTime element with a string for min or max that does not conform to the expected \DateTime format.

### CODE REVIEW

**Comment by jackdpeterson** [comment]
Looks like the unit tests need to be updated now to expect the element to barf when it gets garbage rather than allowing junk in that magically and mysteriously fails.

File: src/Element/DateTime.php [hunk 1]
```diff
@@ -53,7 +54,6 @@ class DateTime extends Element implements InputProviderInterface
     public function setOptions($options)
     {
         parent::setOptions($options);
-
```
Comment (froschdesign) [inline src/Element/DateTime.php]: Please undo all code formatting changes.

File: src/Element/DateTime.php [hunk 2]
```diff
@@ -81,6 +81,7 @@ public function getValue($returnFormattedValue = true)
             return $value;
         }
         $format = $this->getFormat();
+
```
Comment (froschdesign) [inline src/Element/DateTime.php]: Please undo all code formatting changes.

File: src/Element/DateTime.php [hunk 3]
```diff
@@ -92,7 +93,8 @@ public function getValue($returnFormattedValue = true)
      */
     public function setFormat($format)
     {
-        $this->format = (string) $format;
+        $this->format = (string)$format;
```
Comment (froschdesign) [inline src/Element/DateTime.php]: Please undo all code formatting changes.

File: src/Element/DateTime.php [hunk 4]
```diff
@@ -120,32 +122,78 @@ protected function getValidators()
         $validators = [];
         $validators[] = $this->getDateValidator();
 
-        if (isset($this->attributes['min'])) {
-            $validators[] = new GreaterThanValidator([
-                'min'       => $this->attributes['min'],
-                'inclusive' => true,
-            ]);
+        if (isset($this->attributes['min']) &&
+            \DateTime::createFromFormat(
```
Comment (froschdesign) [inline src/Element/DateTime.php]: `createFromFormat` here…

File: src/Element/DateTime.php [hunk 5]
```diff
@@ -120,32 +122,78 @@ protected function getValidators()
...
+            ) instanceof \DateTimeInterface
+        ) {
+            $validators[] = new GreaterThanValidator(
+                [
+                    'min' => $this->attributes['min'],
+                    'inclusive' => true,
+                ]
+            );
+        } elseif (isset($this->attributes['min']) &&
+            ! \DateTime::createFromFormat(
```
Comment (froschdesign) [inline src/Element/DateTime.php]: …and `createFromFormat` here.

Please simplify these if statements.

File: src/Element/DateTime.php [hunk 6]
```diff
@@ -120,32 +122,78 @@ protected function getValidators()
...
+                    $this->attributes['min']
+                )
+            );
         }
-        if (isset($this->attributes['max'])) {
-            $validators[] = new LessThanValidator([
-                'max'       => $this->attributes['max'],
+
+        if (isset($this->attributes['max']) &&
+            \DateTime::createFromFormat(
```
Comment (froschdesign) [inline src/Element/DateTime.php]: The same here…

File: src/Element/DateTime.php [hunk 7]
```diff
@@ -120,32 +122,78 @@ protected function getValidators()
...
+        ) {
+            $validators[] = new LessThanValidator(
+                [
+                'max' => $this->attributes['max'],
                 'inclusive' => true,
-            ]);
+                ]
+            );
+        } elseif (isset($this->attributes['max']) &&
+            ! \DateTime::createFromFormat(
```
Comment (froschdesign) [inline src/Element/DateTime.php]: …and here.

File: src/Element/DateTime.php [hunk 8]
```diff
@@ -155,22 +203,23 @@ protected function getDateValidator()
     /**
      * Retrieves a DateStep Validator configured for a DateTime Input type
      *
-     * @return DateTime
+     * @return DateStepValidator
      */
     protected function getStepValidator()
     {
-        $format    = $this->getFormat();
+        $format = $this->getFormat();
```
Comment (froschdesign) [inline src/Element/DateTime.php]: Please undo all code formatting changes.

File: test/Element/DateTest.php [hunk 9]
```diff
@@ -124,8 +124,8 @@ public function testCorrectFormatPassedToDateValidator()
     {
         $element = new DateElement('foo');
         $element->setAttributes([
-            'min'       => '2012-01-01',
-            'max'       => '2012-12-31',
+            'min'       => '01-01-2012',
```
Comment (froschdesign) [inline test/Element/DateTest.php]: The first rule: Do not change existing unit tests! Changing a unit tests always means a change in behavior.

Can you explain the differences in the values?

File: test/Element/DateTimeLocalTest.php [hunk 10]
```diff
@@ -19,8 +19,8 @@ public function testProvidesInputSpecificationThatIncludesValidatorsBasedOnAttri
         $element = new DateTimeLocalElement('foo');
         $element->setAttributes([
             'inclusive' => true,
-            'min'       => '2000-01-01T00:00Z',
-            'max'       => '2001-01-01T00:00Z',
+            'min'       => '2000-01-01T00:00',
```
Comment (froschdesign) [inline test/Element/DateTimeLocalTest.php]: The same here.

File: test/Element/DateTimeLocalTest.php [hunk 11]
```diff
@@ -40,11 +40,11 @@ public function testProvidesInputSpecificationThatIncludesValidatorsBasedOnAttri
             switch ($class) {
                 case 'Zend\Validator\GreaterThan':
                     $this->assertTrue($validator->getInclusive());
-                    $this->assertEquals('2000-01-01T00:00Z', $validator->getMin());
+                    $this->assertEquals('2000-01-01T00:00', $validator->getMin());
```
Comment (froschdesign) [inline test/Element/DateTimeLocalTest.php]: The same here.

File: test/Element/MonthTest.php [hunk 12]
```diff
@@ -24,6 +24,8 @@ public function testProvidesInputSpecificationThatIncludesValidatorsBasedOnAttri
             'step'      => '1',
         ]);
 
+        $element->setFormat('Y-m');
```
Comment (froschdesign) [inline test/Element/MonthTest.php]: Why is this needed?

File: test/Element/WeekTest.php [hunk 13]
```diff
@@ -24,6 +25,8 @@ public function testProvidesInputSpecificationThatIncludesValidatorsBasedOnAttri
             'step'      => '1',
         ]);
 
+        $element->setFormat('Y-\WW');
```
Comment (froschdesign) [inline test/Element/WeekTest.php]: Why is this needed?

File: test/Element/DateTimeLocalTest.php (hunk 11 above)
Comment (jackdpeterson) [inline test/Element/DateTimeLocalTest.php]: This is the format used in both the documentation and what conforms to the requested \DateTime::createFromFormat string.

File: test/Element/DateTimeLocalTest.php (hunk 10 above)
Comment (jackdpeterson) [inline test/Element/DateTimeLocalTest.php]: Same story -- this is the format that the createFromFormat expects.

File: test/Element/DateTest.php (hunk 9 above)
Comment (jackdpeterson) [inline test/Element/DateTest.php]: The change here is that right below this section is a setFormat(d-m-Y) ... which means that the previous behavior here would yield a broken scenario with values provided that do not properly construct a valid DateTime object -- something I didn't directly test with the Date element; however, since Date extends from DateTime element and uses the parent's methods. This is the behavior that was previously unhandled and the whole point of this PR -- the element expects a very specific format and when it doesn't get that format it fails silently rather than throwing exceptional conditions when handed garbage. If I'm going to keep this unit test mostly the same then I would make this test have an expectedException and create an additional test where the right date is provided and input is properly validated.

**Comment by jackdpeterson** [comment]
I suppose there's also a broader conversation to be had about the changes that I'm implementing here. In the case of the setFormat() bits, I'm assuming that the min and max validation are to be ran off of the same format as the actual input format. This may be an incorrect approach. Rather, I think I'm going to modify this a little bit where the min and max MUST follow the convention for self::DATETIME_FORMAT = 'Y-m-d\TH:iP'; as was the case with my first pass prior to squashing in various other changes. The benefit of this approach would be that the date is always specified in a consistent manner rather than evaluated based on the then-current format.

Either way, the current implementation has problems and I think the above should be discussed. Locking down to one format for the min / max seems to be the most appropriate choice. Either way, unit tests must be modified.

**Comment by jackdpeterson** [comment]
Branch updated w/ additional unit tests to reflect which scenarios fail. Also fixed on unit test related to the DateTimeLocalElement where an invalid specification was provided that was inconsistent w/ the [documentation](https://docs.zendframework.com/zend-form/element/date-time-local/).

File: test/Element/DateTimeLocalTest.php (hunk 10 above)
Comment (jackdpeterson) [inline test/Element/DateTimeLocalTest.php]: This test was updated to be consistent w/ the documentation. Additional test added when an invalid min/max specification like the one above is added that would result in an InvalidArgumentException.

File: test/Element/DateTimeLocalTest.php (hunk 11 above)
Comment (jackdpeterson) [inline test/Element/DateTimeLocalTest.php]: This test was updated to be consistent w/ the documentation. Additional test added when an invalid min/max specification like the one above is added that would result in an InvalidArgumentException.

File: src/Element/DateTime.php (hunk 5 above)
Comment (jackdpeterson) [inline src/Element/DateTime.php]: This logic is correct and intended to be this way. No further simplifications are necessary. Are you proposing creating and referencing unecessary variables simply for the sake of reducing how the logic works?

File: src/Element/DateTime.php (hunk 4 above)
Comment (jackdpeterson) [inline src/Element/DateTime.php]: This logic is correct and intended to be this way. No further simplifications are necessary. Are you proposing creating and referencing unecessary variables simply for the sake of reducing how the logic works?

File: src/Element/DateTime.php (hunk 6 above)
Comment (jackdpeterson) [inline src/Element/DateTime.php]: Same response as above -- this logic is intended to be this way and has backing unit tests added.

File: src/Element/DateTime.php (hunk 7 above)
Comment (jackdpeterson) [inline src/Element/DateTime.php]: See other responses. Again, intentional :-P

**Comment by jackdpeterson** [comment]
Are there other comments on this PR or can we move this into the next minor release of Zend-Form?

File: src/Element/DateTime.php (hunk 4 above)
Comment (froschdesign) [inline src/Element/DateTime.php]: You can remove the `DateTime::createFromFormat()` from the condition and the `elseif` can be eliminated.

At the moment the entire block is hard to read.

**Comment by froschdesign** [comment]
@jackdpeterson 
Throw an exception is a new behaviour.
Can we cover the old and the new behaviour with unit tests to prevent any problems in existing applications / forms?

**Comment by jackdpeterson** [comment]
@froschdesign -- see the changes for the tests folder. I also added a unit tests for specific areas where invalid specifications are provided.

**Comment by froschdesign** [comment]
Btw. if the documentation is wrong or a bug is included, then we must fix this!

```php
$dateTimeLocal->setAttributes([
    'min'  => '2010-01-01T00:00:00',
    'max'  => '2020-01-01T00:00:00',
    'step' => '1', // minutes; default step interval is 1 min
]);
$dateTimeLocal->setOptions([
    'format' => 'Y-m-d\TH:i',
]);
```

https://docs.zendframework.com/zend-form/element/date-time-local/#basic-usage

File: src/Element/DateTime.php (hunk 4 above)
Comment (froschdesign) [inline src/Element/DateTime.php]: Please simplify the if statements.

Comment (weierophinney) [inline src/Element/DateTime.php]: Honestly, I agree with @froschdesign here. The same multiline statement is used in multiple conditions, making those conditions really hard to read. Capturing to a variable makes the conditions easier to read.

I can do that on merge.

File: test/Element/DateTimeLocalTest.php (hunk 11 above)
Comment (weierophinney) [inline test/Element/DateTimeLocalTest.php]: I think the test changes make sense. The originals were based on an invalid assumption.

**Comment by weierophinney** [comment]
Thanks, @jackdpeterson
